package com.penmate.backend.application.agent.run;

import com.penmate.backend.application.agent.tool.runtime.ToolCallResult;
import com.penmate.backend.application.common.serialization.JsonCodec;
import com.penmate.backend.domain.agent.repository.AgentSessionRepository;
import com.penmate.backend.domain.agent.run.model.AgentRun;
import com.penmate.backend.domain.agent.run.model.AgentRunInput;
import com.penmate.backend.domain.agent.run.model.AgentToolCallExecution;
import com.penmate.backend.domain.agent.run.model.AgentToolCallExecutionStatus;
import com.penmate.backend.domain.agent.run.repository.AgentRunRepository;
import com.penmate.backend.domain.agent.run.repository.AgentToolCallExecutionRepository;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

@Service
public class AgentRunRecoveryPromptService {

    static final String RECOVERY_HEADER = "[Application recovery record]";
    static final String CURRENT_REQUEST_HEADER = "[Current user request]";
    private static final Set<String> INTERRUPTED_STATUSES = Set.of("FAILED", "CANCELLED");
    private static final int MAX_ATTEMPTS = 8;
    private static final int MAX_TOOL_EXECUTIONS = 32;
    private static final int MAX_REQUEST_CHARS = 1_200;
    private static final int MAX_RESULT_CHARS = 800;

    private final AgentRunRepository runs;
    private final AgentToolCallExecutionRepository toolExecutions;
    private final AgentSessionRepository sessions;
    private final JsonCodec json;

    public AgentRunRecoveryPromptService(AgentRunRepository runs,
                                         AgentToolCallExecutionRepository toolExecutions,
                                         AgentSessionRepository sessions,
                                         JsonCodec json) {
        this.runs = runs;
        this.toolExecutions = toolExecutions;
        this.sessions = sessions;
        this.json = json;
    }

    public String attachToManualRequest(Long projectId, Long sessionId, String currentRequest) {
        String request = currentRequest == null ? "" : currentRequest;
        List<AgentRun> interrupted = interruptedTail(runs.listBySession(projectId, sessionId));
        if (interrupted.isEmpty()) return request;

        Map<String, String> userRequestsByTurn = userRequestsByTurn(sessionId);
        StringBuilder recovery = new StringBuilder(RECOVERY_HEADER).append('\n')
                .append("This record was generated by the application from durable execution data.\n")
                .append("Succeeded tool results describe work already performed. Do not repeat state-changing ")
                .append("operations whose results show they were applied. Read current state again when needed.\n")
                .append("The current user request below remains authoritative.\n");

        int remainingToolExecutions = MAX_TOOL_EXECUTIONS;
        for (AgentRun run : interrupted) {
            recovery.append("\nAttempt runId=").append(run.runId())
                    .append(" status=").append(normalizeStatus(run.runStatus())).append('\n');
            String originalRequest = userRequestsByTurn.get(String.valueOf(run.turnId()));
            if (originalRequest == null || originalRequest.isBlank()) {
                originalRequest = fallbackRequest(run.runId());
            }
            if (originalRequest != null && !originalRequest.isBlank()) {
                recovery.append("Original request: ")
                        .append(singleLine(originalRequest, MAX_REQUEST_CHARS)).append('\n');
            }
            if (run.lastErrorCode() != null || run.lastErrorMessage() != null) {
                recovery.append("Terminal error: ")
                        .append(singleLine(run.lastErrorCode(), 96)).append(' ')
                        .append(singleLine(run.lastErrorMessage(), 500)).append('\n');
            }

            List<AgentToolCallExecution> executions = safeList(toolExecutions.listByRun(run.runId()));
            if (executions.isEmpty()) {
                recovery.append("Tool executions: none recorded\n");
                continue;
            }
            for (AgentToolCallExecution execution : executions) {
                if (remainingToolExecutions-- <= 0) {
                    recovery.append("Tool executions: additional records omitted\n");
                    break;
                }
                recovery.append("- tool=").append(singleLine(execution.toolCode(), 100))
                        .append(" status=").append(execution.status().name());
                String detail = executionDetail(execution);
                if (!detail.isBlank()) recovery.append(" detail=").append(detail);
                recovery.append('\n');
            }
            if (remainingToolExecutions < 0) break;
        }

        return recovery.append('\n').append(CURRENT_REQUEST_HEADER).append('\n').append(request).toString();
    }

    private List<AgentRun> interruptedTail(List<AgentRun> sessionRuns) {
        List<AgentRun> source = safeList(sessionRuns);
        if (source.isEmpty()) return List.of();
        List<AgentRun> reversed = new ArrayList<>();
        for (int index = source.size() - 1; index >= 0 && reversed.size() < MAX_ATTEMPTS; index--) {
            AgentRun run = source.get(index);
            if (run == null || !INTERRUPTED_STATUSES.contains(normalizeStatus(run.runStatus()))) break;
            reversed.add(run);
        }
        Collections.reverse(reversed);
        return List.copyOf(reversed);
    }

    private Map<String, String> userRequestsByTurn(Long sessionId) {
        Map<String, String> result = new LinkedHashMap<>();
        for (Map<String, Object> row : safeList(sessions.listMessageRows(sessionId))) {
            if (!"user".equalsIgnoreCase(String.valueOf(row.get("role")))) continue;
            Object turnId = row.get("turnId");
            Object content = row.get("contentMarkdown");
            if (turnId != null && content != null) {
                result.put(String.valueOf(turnId), String.valueOf(content));
            }
        }
        return result;
    }

    private String fallbackRequest(Long runId) {
        AgentRunInput input = runs.findInput(runId);
        if (input == null || input.promptSnapshot() == null) return "";
        String prompt = input.promptSnapshot();
        int currentRequest = prompt.lastIndexOf(CURRENT_REQUEST_HEADER);
        return currentRequest < 0 ? prompt : prompt.substring(currentRequest + CURRENT_REQUEST_HEADER.length()).trim();
    }

    private String executionDetail(AgentToolCallExecution execution) {
        if (execution.status() == AgentToolCallExecutionStatus.AMBIGUOUS) {
            return singleLine(execution.errorMessage(), 500);
        }
        if (execution.resultJson() != null && !execution.resultJson().isBlank()) {
            try {
                ToolCallResult result = json.read(execution.resultJson(), ToolCallResult.class);
                if (result.toolOutput() != null && !result.toolOutput().isBlank()) {
                    return singleLine(result.toolOutput(), MAX_RESULT_CHARS);
                }
                if (result.errorMessage() != null && !result.errorMessage().isBlank()) {
                    return singleLine(result.errorCode() + ": " + result.errorMessage(), MAX_RESULT_CHARS);
                }
            } catch (IllegalArgumentException ignored) {
                return "stored result is unreadable";
            }
        }
        String error = String.join(": ", safeText(execution.errorCode()), safeText(execution.errorMessage()))
                .replaceFirst("^: ", "").replaceFirst(": $", "");
        return singleLine(error, MAX_RESULT_CHARS);
    }

    private String normalizeStatus(String value) {
        return value == null ? "UNKNOWN" : value.trim().toUpperCase(Locale.ROOT);
    }

    private String singleLine(String value, int maxChars) {
        String normalized = safeText(value).replaceAll("\\s+", " ").trim();
        if (normalized.length() <= maxChars) return normalized;
        return normalized.substring(0, maxChars) + "...";
    }

    private String safeText(String value) {
        return value == null ? "" : value;
    }

    private <T> List<T> safeList(List<T> value) {
        return value == null ? List.of() : value;
    }
}
