CREATE TABLE IF NOT EXISTS agent_run_pending_approvals (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    pending_approval_id BIGINT UNSIGNED NOT NULL,
    approval_id BIGINT UNSIGNED NOT NULL,
    run_id BIGINT UNSIGNED NOT NULL,
    project_id BIGINT UNSIGNED NOT NULL,
    session_id BIGINT UNSIGNED NOT NULL,
    turn_id BIGINT UNSIGNED NOT NULL,
    tool_call_id VARCHAR(128) NOT NULL,
    tool_code VARCHAR(100) NOT NULL,
    tool_args_json LONGTEXT NULL,
    tool_context_json LONGTEXT NULL,
    resume_payload_json LONGTEXT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    pending_status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    operator_id BIGINT UNSIGNED NULL,
    trace_id VARCHAR(64) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_agent_run_pending_approvals_pending_id (pending_approval_id),
    UNIQUE KEY uk_agent_run_pending_approvals_approval_id (approval_id),
    UNIQUE KEY uk_agent_run_pending_approvals_idempotency (idempotency_key),
    KEY idx_agent_run_pending_approvals_run_status (run_id, pending_status),
    KEY idx_agent_run_pending_approvals_session_status (session_id, pending_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
