CREATE TABLE novel_import_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    source_format VARCHAR(20) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    draft_json JSONB NOT NULL,
    status VARCHAR(20) NOT NULL,
    project_id BIGINT NULL,
    job_id BIGINT NULL,
    checkpoint_chapter INTEGER NOT NULL DEFAULT 0,
    total_chapters INTEGER NOT NULL,
    error_message VARCHAR(1000) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_novel_import_session_id UNIQUE (session_id)
);

CREATE INDEX idx_novel_import_owner_created
    ON novel_import_sessions (owner_user_id, created_at DESC);
CREATE INDEX idx_novel_import_job
    ON novel_import_sessions (job_id) WHERE job_id IS NOT NULL;

CREATE TABLE novel_import_volume_map (
    session_id BIGINT NOT NULL,
    volume_index INTEGER NOT NULL,
    volume_id BIGINT NOT NULL,
    PRIMARY KEY (session_id, volume_index),
    CONSTRAINT fk_novel_import_volume_session
        FOREIGN KEY (session_id) REFERENCES novel_import_sessions(session_id) ON DELETE CASCADE
);
