-- PostgreSQL 18.4 baseline: V1__create_iam_and_rbac.sql

-- Source: V1__init_iam_and_rbac.sql
CREATE TABLE IF NOT EXISTS iam_users (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    status SMALLINT NOT NULL DEFAULT 1,
    auth_method VARCHAR(32) NOT NULL DEFAULT 'local',
    main_agent_model_config_id BIGINT NULL,
    dirty_work_agent_model_config_id BIGINT NULL,
    last_login_at TIMESTAMPTZ(3) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_iam_users_user_id UNIQUE (user_id)
);

CREATE INDEX idx_iam_users_status_deleted ON iam_users (status, deleted_at);
CREATE UNIQUE INDEX uk_iam_users_email_active ON iam_users (lower(email)) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS iam_roles (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(100) NOT NULL,
    description VARCHAR(255) NULL,
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_iam_roles_role_id UNIQUE (role_id)
);

CREATE UNIQUE INDEX uk_iam_roles_code_active ON iam_roles (lower(code)) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS iam_permissions (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(120) NOT NULL,
    module VARCHAR(60) NOT NULL,
    description VARCHAR(255) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_iam_permissions_permission_id UNIQUE (permission_id)
);

CREATE UNIQUE INDEX uk_iam_permissions_code ON iam_permissions (lower(code));

CREATE TABLE IF NOT EXISTS iam_user_roles (

    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (user_id, role_id)
);

CREATE INDEX idx_user_roles_role_user ON iam_user_roles (role_id, user_id);

CREATE TABLE IF NOT EXISTS iam_role_permissions (

    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (role_id, permission_id)
);

CREATE INDEX idx_role_perm_perm_role ON iam_role_permissions (permission_id, role_id);


-- Source: V7__init_iam_menus.sql
CREATE TABLE IF NOT EXISTS iam_menus (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id BIGINT NOT NULL,
    parent_id BIGINT NULL,
    title VARCHAR(100) NOT NULL,
    path VARCHAR(255) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    permission_code VARCHAR(120) NULL,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_iam_menus_menu_id UNIQUE (menu_id)
);

CREATE INDEX idx_menu_parent_sort ON iam_menus (parent_id, sort_order);
CREATE INDEX idx_menu_visible ON iam_menus (visible, deleted_at);
