-- PostgreSQL 18.4 baseline: V1__create_iam_and_rbac.sql

-- Source: V1__init_iam_and_rbac.sql
CREATE TABLE IF NOT EXISTS iam_users (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    bio VARCHAR(500) NOT NULL DEFAULT '',
    status SMALLINT NOT NULL DEFAULT 1,
    auth_method VARCHAR(32) NOT NULL DEFAULT 'local',
    last_login_at TIMESTAMPTZ(3) NULL,
    deletion_requested_at TIMESTAMPTZ(3) NULL,
    deletion_due_at TIMESTAMPTZ(3) NULL,
    rbac_revision BIGINT NOT NULL DEFAULT 0,
    authorization_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_iam_users_user_id UNIQUE (user_id),
    CONSTRAINT ck_iam_users_auth_method CHECK (auth_method = 'local')
);

CREATE INDEX idx_iam_users_status_deleted ON iam_users (status, deleted_at);
CREATE INDEX idx_iam_users_deletion_due ON iam_users (deletion_due_at) WHERE deletion_requested_at IS NOT NULL;
CREATE UNIQUE INDEX uk_iam_users_email_active ON iam_users (lower(email)) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS auth_sessions (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    current_access_jti VARCHAR(64) NOT NULL,
    current_refresh_jti_hash VARCHAR(64) NOT NULL,
    device_name VARCHAR(120) NOT NULL,
    browser_name VARCHAR(80) NOT NULL,
    operating_system VARCHAR(80) NOT NULL,
    user_agent VARCHAR(500) NOT NULL,
    ip_address VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    last_seen_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    refresh_expires_at TIMESTAMPTZ(3) NOT NULL,
    revoked_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_auth_sessions_session_id UNIQUE (session_id)
);

CREATE INDEX idx_auth_sessions_user_active ON auth_sessions (user_id, revoked_at, last_seen_at DESC);
CREATE UNIQUE INDEX uk_auth_sessions_refresh_jti_active
    ON auth_sessions (current_refresh_jti_hash) WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS user_ui_preferences (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    theme_mode VARCHAR(16) NOT NULL DEFAULT 'SYSTEM',
    editor_font_family VARCHAR(16) NOT NULL DEFAULT 'SERIF',
    editor_font_size INTEGER NOT NULL DEFAULT 17,
    editor_line_height NUMERIC(3, 2) NOT NULL DEFAULT 1.90,
    editor_paragraph_spacing NUMERIC(3, 2) NOT NULL DEFAULT 0.35,
    editor_content_width INTEGER NOT NULL DEFAULT 760,
    typewriter_mode BOOLEAN NOT NULL DEFAULT FALSE,
    highlight_current_paragraph BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_user_ui_preferences_user UNIQUE (user_id),
    CONSTRAINT ck_user_ui_preferences_theme CHECK (theme_mode IN ('SYSTEM', 'LIGHT', 'DARK')),
    CONSTRAINT ck_user_ui_preferences_font CHECK (editor_font_family IN ('SERIF', 'SANS', 'SYSTEM')),
    CONSTRAINT ck_user_ui_preferences_font_size CHECK (editor_font_size BETWEEN 14 AND 24),
    CONSTRAINT ck_user_ui_preferences_line_height CHECK (editor_line_height BETWEEN 1.50 AND 2.40),
    CONSTRAINT ck_user_ui_preferences_paragraph_spacing CHECK (editor_paragraph_spacing BETWEEN 0 AND 2.00),
    CONSTRAINT ck_user_ui_preferences_content_width CHECK (editor_content_width BETWEEN 560 AND 1000)
);

CREATE TABLE IF NOT EXISTS iam_roles (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(100) NOT NULL,
    description VARCHAR(255) NULL,
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    rbac_revision BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_iam_roles_role_id UNIQUE (role_id)
);

CREATE UNIQUE INDEX uk_iam_roles_code_active ON iam_roles (lower(code)) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS iam_permissions (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(120) NOT NULL,
    module VARCHAR(60) NOT NULL,
    description VARCHAR(255) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_iam_permissions_permission_id UNIQUE (permission_id)
);

CREATE UNIQUE INDEX uk_iam_permissions_code ON iam_permissions (lower(code));

CREATE TABLE IF NOT EXISTS iam_user_roles (

    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (user_id, role_id)
);

CREATE INDEX idx_user_roles_role_user ON iam_user_roles (role_id, user_id);

CREATE TABLE IF NOT EXISTS iam_role_permissions (

    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (role_id, permission_id)
);

CREATE INDEX idx_role_perm_perm_role ON iam_role_permissions (permission_id, role_id);

CREATE TABLE IF NOT EXISTS iam_rbac_assignment_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_id BIGINT NOT NULL,
    actor_user_id BIGINT NOT NULL,
    assignment_type VARCHAR(40) NOT NULL,
    target_id BIGINT NOT NULL,
    before_ids_json JSONB NOT NULL,
    after_ids_json JSONB NOT NULL,
    previous_revision BIGINT NOT NULL,
    new_revision BIGINT NOT NULL,
    trace_id VARCHAR(64) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_iam_rbac_assignment_audits_id UNIQUE (audit_id),
    CONSTRAINT ck_iam_rbac_assignment_audits_type CHECK (
        assignment_type IN ('USER_ROLES', 'ROLE_PERMISSIONS')
    )
);

CREATE INDEX idx_iam_rbac_assignment_audits_target
    ON iam_rbac_assignment_audits (assignment_type, target_id, created_at DESC);
CREATE INDEX idx_iam_rbac_assignment_audits_actor
    ON iam_rbac_assignment_audits (actor_user_id, created_at DESC);


-- Source: V7__init_iam_menus.sql
CREATE TABLE IF NOT EXISTS iam_menus (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id BIGINT NOT NULL,
    parent_id BIGINT NULL,
    title VARCHAR(100) NOT NULL,
    path VARCHAR(255) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    permission_code VARCHAR(120) NULL,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_iam_menus_menu_id UNIQUE (menu_id)
);

CREATE INDEX idx_menu_parent_sort ON iam_menus (parent_id, sort_order);
CREATE INDEX idx_menu_visible ON iam_menus (visible, deleted_at);
