-- PostgreSQL 18.4 baseline: V2__create_novel_and_story_domain.sql

-- Source: V2__init_novel_and_approval_minimal.sql
CREATE TABLE IF NOT EXISTS novel_projects (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    summary TEXT NULL,
    status SMALLINT NOT NULL DEFAULT 1,
    structure_revision BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_novel_projects_project_id UNIQUE (project_id)
);

CREATE INDEX idx_novel_owner_status ON novel_projects (owner_user_id, status, deleted_at);

CREATE TABLE IF NOT EXISTS agent_approval_requests (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approval_request_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    run_id BIGINT NULL,
    approval_type VARCHAR(40) NOT NULL,
    payload_json JSONB NOT NULL,
    risk_level SMALLINT NOT NULL DEFAULT 2,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    requested_by BIGINT NOT NULL,
    reviewed_by BIGINT NULL,
    reviewed_at TIMESTAMPTZ(3) NULL,
    review_comment VARCHAR(500) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_approval_requests_request_id UNIQUE (approval_request_id)
);

CREATE INDEX idx_approval_project_status ON agent_approval_requests (project_id, status, created_at);
CREATE INDEX idx_approval_run ON agent_approval_requests (run_id);

CREATE TABLE IF NOT EXISTS agent_approval_actions (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approval_action_id BIGINT NOT NULL,
    request_id BIGINT NOT NULL,
    action VARCHAR(20) NOT NULL,
    operator_id BIGINT NOT NULL,
    comment VARCHAR(500) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_approval_actions_action_id UNIQUE (approval_action_id)
);

CREATE INDEX idx_approval_actions_request ON agent_approval_actions (request_id, created_at);



-- Source: V4__init_novel_volume_and_chapter.sql
CREATE TABLE IF NOT EXISTS novel_volumes (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    volume_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    description TEXT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_novel_volumes_volume_id UNIQUE (volume_id)
);

CREATE INDEX idx_volume_project_sort ON novel_volumes (project_id, sort_order, deleted_at);

CREATE TABLE IF NOT EXISTS novel_chapters (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chapter_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    volume_id BIGINT NULL,
    outline_node_id BIGINT NULL,
    title VARCHAR(200) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status SMALLINT NOT NULL DEFAULT 1,
    word_count INTEGER NOT NULL DEFAULT 0,
    excerpt TEXT NULL,
    content_object_key VARCHAR(500) NOT NULL,
    content_etag VARCHAR(128) NULL,
    content_size BIGINT NULL,
    content_checksum VARCHAR(128) NULL,
    storage_provider VARCHAR(32) NOT NULL DEFAULT 's3',
    content_revision BIGINT NOT NULL DEFAULT 1,
    last_generated_at TIMESTAMPTZ(3) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_novel_chapters_chapter_id UNIQUE (chapter_id)
);

CREATE INDEX idx_chapter_project_volume_sort ON novel_chapters (project_id, volume_id, sort_order, deleted_at);
CREATE INDEX idx_chapter_outline ON novel_chapters (outline_node_id);
CREATE INDEX idx_chapter_content_object ON novel_chapters (content_object_key);



-- Chapter versions are immutable OSS snapshots. Project ownership is defined only
-- by novel_projects.owner_user_id; there is no collaboration membership table.
CREATE TABLE IF NOT EXISTS novel_chapter_versions (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chapter_version_id BIGINT NOT NULL,
    chapter_id BIGINT NOT NULL,
    version_no INTEGER NOT NULL,
    change_type VARCHAR(32) NOT NULL,
    change_reason VARCHAR(255) NULL,
    snapshot_object_key VARCHAR(500) NOT NULL,
    snapshot_etag VARCHAR(128) NULL,
    snapshot_size BIGINT NULL,
    snapshot_checksum VARCHAR(128) NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_novel_chapter_versions_version_id UNIQUE (chapter_version_id),
    CONSTRAINT uk_chapter_version_no UNIQUE (chapter_id, version_no)
);

CREATE INDEX idx_chapter_versions_chapter_created ON novel_chapter_versions (chapter_id, created_at);



-- Source: V8__init_novel_outlines_and_cards.sql
CREATE TABLE IF NOT EXISTS novel_outline_nodes (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outline_node_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    parent_id BIGINT NULL,
    title VARCHAR(200) NOT NULL,
    node_type VARCHAR(40) NOT NULL DEFAULT 'chapter',
    sort_order INTEGER NOT NULL DEFAULT 0,
    content TEXT NULL,
    revision BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_novel_outline_nodes_outline_node_id UNIQUE (outline_node_id)
);

CREATE INDEX idx_outline_project_parent_sort ON novel_outline_nodes (project_id, parent_id, sort_order, deleted_at);



-- Source: V9__init_style_profiles.sql
CREATE TABLE IF NOT EXISTS style_profiles (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    style_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    pace VARCHAR(50) NULL,
    tone VARCHAR(50) NULL,
    narrative_focus VARCHAR(100) NULL,
    prompt_template TEXT NULL,
    sample_text TEXT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_style_profiles_style_id UNIQUE (style_id)
);

CREATE INDEX idx_style_project_deleted ON style_profiles (project_id, deleted_at);
CREATE INDEX idx_style_project_default ON style_profiles (project_id, is_default, deleted_at);

CREATE TABLE IF NOT EXISTS style_switch_logs (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    style_switch_log_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    from_style_id BIGINT NULL,
    to_style_id BIGINT NOT NULL,
    switched_by BIGINT NOT NULL,
    warning_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    reason VARCHAR(255) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_style_switch_logs_log_id UNIQUE (style_switch_log_id)
);

CREATE INDEX idx_style_switch_project_created ON style_switch_logs (project_id, created_at);


-- Source: V14__init_story_bible_domain.sql
CREATE TABLE IF NOT EXISTS story_bibles (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_bible_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT NULL,
    content_revision BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_story_bibles_story_bible_id UNIQUE (story_bible_id),
    CONSTRAINT uk_story_bibles_project_id UNIQUE (project_id)
);

CREATE TABLE IF NOT EXISTS story_bible_node_types (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id BIGINT NOT NULL,
    story_bible_id BIGINT NULL,
    type_code VARCHAR(80) NOT NULL,
    semantic_family VARCHAR(40) NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    icon_code VARCHAR(80) NULL,
    field_schema_json JSONB NOT NULL,
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    archived_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_story_bible_node_types_type_id UNIQUE (type_id),
    CONSTRAINT uk_story_bible_node_types_scope_code UNIQUE (story_bible_id, type_code)
);

CREATE INDEX idx_story_bible_node_types_family ON story_bible_node_types (story_bible_id, semantic_family, archived_at, sort_order);

CREATE TABLE IF NOT EXISTS story_bible_nodes (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id BIGINT NOT NULL,
    story_bible_id BIGINT NOT NULL,
    type_id BIGINT NOT NULL,
    title VARCHAR(240) NOT NULL,
    summary TEXT NULL,
    body_markdown TEXT NULL,
    attributes_json JSONB NOT NULL,
    inclusion_policy VARCHAR(24) NOT NULL DEFAULT 'AUTO_RETRIEVE',
    canon_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    revision BIGINT NOT NULL DEFAULT 1,
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    archived_at TIMESTAMPTZ(3) NULL,
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_story_bible_nodes_node_id UNIQUE (node_id)
);

CREATE INDEX idx_story_bible_nodes_scope ON story_bible_nodes (story_bible_id, type_id, canon_status, deleted_at);
CREATE INDEX idx_story_bible_nodes_title ON story_bible_nodes (story_bible_id, title);

CREATE TABLE IF NOT EXISTS story_bible_aliases (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias_id BIGINT NOT NULL,
    story_bible_id BIGINT NOT NULL,
    node_id BIGINT NOT NULL,
    alias VARCHAR(240) NOT NULL,
    normalized_alias VARCHAR(240) NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_story_bible_aliases_alias_id UNIQUE (alias_id),
    CONSTRAINT uk_story_bible_aliases_normalized UNIQUE (story_bible_id, normalized_alias, node_id)
);

CREATE INDEX idx_story_bible_aliases_node ON story_bible_aliases (node_id, deleted_at);

CREATE TABLE IF NOT EXISTS story_bible_categories (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    story_bible_id BIGINT NOT NULL,
    parent_category_id BIGINT NULL,
    name VARCHAR(120) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_story_bible_categories_category_id UNIQUE (category_id),
    CONSTRAINT uk_story_bible_categories_sibling_name UNIQUE (story_bible_id, parent_category_id, name)
);

CREATE INDEX idx_story_bible_categories_tree ON story_bible_categories (story_bible_id, parent_category_id, sort_order, deleted_at);

CREATE TABLE IF NOT EXISTS story_bible_node_categories (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_bible_id BIGINT NOT NULL,
    node_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_story_bible_node_categories_membership UNIQUE (node_id, category_id)
);

CREATE INDEX idx_story_bible_node_categories_category ON story_bible_node_categories (story_bible_id, category_id, node_id);

CREATE TABLE IF NOT EXISTS story_bible_tags (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_id BIGINT NOT NULL,
    story_bible_id BIGINT NOT NULL,
    name VARCHAR(80) NOT NULL,
    normalized_name VARCHAR(80) NOT NULL,
    color VARCHAR(20) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_story_bible_tags_tag_id UNIQUE (tag_id),
    CONSTRAINT uk_story_bible_tags_name UNIQUE (story_bible_id, normalized_name)
);

CREATE INDEX idx_story_bible_tags_scope ON story_bible_tags (story_bible_id, deleted_at);

CREATE TABLE IF NOT EXISTS story_bible_node_tags (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_bible_id BIGINT NOT NULL,
    node_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_story_bible_node_tags_membership UNIQUE (node_id, tag_id)
);

CREATE INDEX idx_story_bible_node_tags_tag ON story_bible_node_tags (story_bible_id, tag_id, node_id);

CREATE TABLE IF NOT EXISTS story_bible_relations (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id BIGINT NOT NULL,
    story_bible_id BIGINT NOT NULL,
    source_node_id BIGINT NOT NULL,
    relation_type VARCHAR(80) NOT NULL,
    target_node_id BIGINT NOT NULL,
    description TEXT NULL,
    attributes_json JSONB NOT NULL,
    revision BIGINT NOT NULL DEFAULT 1,
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_story_bible_relations_relation_id UNIQUE (relation_id),
    CONSTRAINT uk_story_bible_relations_edge UNIQUE (story_bible_id, source_node_id, relation_type, target_node_id)
);

CREATE INDEX idx_story_bible_relations_target ON story_bible_relations (story_bible_id, target_node_id, deleted_at);

CREATE TABLE IF NOT EXISTS story_bible_progressions (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    progression_id BIGINT NOT NULL,
    story_bible_id BIGINT NOT NULL,
    node_id BIGINT NOT NULL,
    anchor_chapter_id BIGINT NOT NULL,
    end_chapter_id BIGINT NULL,
    story_event_node_id BIGINT NULL,
    patch_json JSONB NOT NULL,
    summary VARCHAR(500) NULL,
    revision BIGINT NOT NULL DEFAULT 1,
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_story_bible_progressions_progression_id UNIQUE (progression_id)
);

CREATE INDEX idx_story_bible_progressions_effective ON story_bible_progressions (story_bible_id, node_id, anchor_chapter_id, end_chapter_id, deleted_at);
CREATE INDEX idx_story_bible_progressions_event ON story_bible_progressions (story_event_node_id);

CREATE TABLE IF NOT EXISTS story_bible_view_preferences (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_bible_id BIGINT NOT NULL,
    view_code VARCHAR(40) NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    hidden BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL,
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_story_bible_view_preferences_view UNIQUE (story_bible_id, view_code)
);

CREATE INDEX idx_story_bible_view_preferences_order ON story_bible_view_preferences (story_bible_id, sort_order);

CREATE TABLE IF NOT EXISTS story_bible_changesets (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    changeset_id BIGINT NOT NULL,
    story_bible_id BIGINT NOT NULL,
    content_revision BIGINT NOT NULL,
    actor_type VARCHAR(20) NOT NULL,
    actor_id BIGINT NOT NULL,
    source_run_id BIGINT NULL,
    change_summary VARCHAR(500) NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_story_bible_changesets_changeset_id UNIQUE (changeset_id),
    CONSTRAINT uk_story_bible_changesets_revision UNIQUE (story_bible_id, content_revision)
);

CREATE INDEX idx_story_bible_changesets_retention ON story_bible_changesets (story_bible_id, created_at, changeset_id);

CREATE TABLE IF NOT EXISTS story_bible_change_items (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    change_item_id BIGINT NOT NULL,
    changeset_id BIGINT NOT NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id BIGINT NOT NULL,
    operation VARCHAR(20) NOT NULL,
    field_path VARCHAR(500) NOT NULL,
    before_json JSONB NULL,
    after_json JSONB NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_story_bible_change_items_item_id UNIQUE (change_item_id)
);

CREATE INDEX idx_story_bible_change_items_changeset ON story_bible_change_items (changeset_id, change_item_id);
CREATE INDEX idx_story_bible_change_items_entity ON story_bible_change_items (entity_type, entity_id, created_at);
