-- PostgreSQL 18.4 + pgvector 0.8.5 baseline: storage and derived knowledge index.
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

CREATE TABLE storage_objects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_object_id BIGINT NOT NULL,
    object_key VARCHAR(500) NOT NULL,
    bucket VARCHAR(100) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    region VARCHAR(64) NULL,
    etag VARCHAR(128) NULL,
    size BIGINT NULL,
    checksum VARCHAR(128) NULL,
    storage_class VARCHAR(32) NULL,
    ref_type VARCHAR(50) NOT NULL,
    ref_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_storage_objects_storage_object_id UNIQUE (storage_object_id),
    CONSTRAINT uk_storage_object_key UNIQUE (object_key)
);

CREATE INDEX idx_storage_ref ON storage_objects (ref_type, ref_id, deleted_at);

CREATE TABLE rag_upload_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    doc_type VARCHAR(32) NOT NULL DEFAULT 'KNOWLEDGE_DOCUMENT',
    title VARCHAR(200) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    file_extension VARCHAR(16) NOT NULL,
    declared_mime_type VARCHAR(100) NOT NULL,
    expected_size BIGINT NOT NULL,
    expected_checksum VARCHAR(128) NULL,
    object_key VARCHAR(500) NOT NULL,
    upload_token_hash CHAR(64) NOT NULL,
    upload_status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    expires_at TIMESTAMPTZ(3) NOT NULL,
    completed_at TIMESTAMPTZ(3) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_rag_upload_sessions_upload_id UNIQUE (upload_id),
    CONSTRAINT uk_rag_upload_sessions_object_key UNIQUE (object_key),
    CONSTRAINT ck_rag_upload_status CHECK (upload_status IN ('PENDING', 'COMPLETED', 'EXPIRED', 'REJECTED')),
    CONSTRAINT ck_rag_upload_size CHECK (expected_size > 0 AND expected_size <= 10485760)
);

CREATE INDEX idx_rag_upload_owner_status ON rag_upload_sessions (owner_user_id, project_id, upload_status, expires_at);

CREATE TABLE rag_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    doc_type VARCHAR(32) NOT NULL,
    title VARCHAR(200) NOT NULL,
    source_ref VARCHAR(500) NULL,
    origin_object_key VARCHAR(500) NOT NULL,
    origin_etag VARCHAR(128) NULL,
    origin_checksum VARCHAR(128) NULL,
    origin_size BIGINT NULL,
    file_extension VARCHAR(16) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    source_revision BIGINT NOT NULL DEFAULT 1,
    parse_status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    index_status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    last_error_code VARCHAR(96) NULL,
    last_error_message VARCHAR(500) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_rag_documents_document_id UNIQUE (document_id)
);

CREATE INDEX idx_rag_project_status ON rag_documents (project_id, parse_status, index_status, deleted_at);
CREATE INDEX idx_rag_document_object ON rag_documents (origin_object_key, deleted_at);

CREATE TABLE project_ai_configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_ai_config_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    creative_model_config_id BIGINT NULL,
    embedding_model_config_id BIGINT NULL,
    story_bible_routing_mode VARCHAR(32) NOT NULL DEFAULT 'LLM_SELECTOR',
    router_model_config_id BIGINT NULL,
    chunk_target_characters INTEGER NOT NULL DEFAULT 800,
    chunk_overlap_characters INTEGER NOT NULL DEFAULT 120,
    chunk_max_characters INTEGER NOT NULL DEFAULT 1200,
    retrieval_candidates INTEGER NOT NULL DEFAULT 30,
    retrieval_top_k INTEGER NOT NULL DEFAULT 8,
    retrieval_max_per_source INTEGER NOT NULL DEFAULT 3,
    hnsw_ef_search INTEGER NOT NULL DEFAULT 100,
    similarity_threshold NUMERIC(12,8) NULL,
    index_status VARCHAR(32) NOT NULL DEFAULT 'UNBOUND',
    active_index_build_id BIGINT NULL,
    last_error_code VARCHAR(96) NULL,
    last_error_message VARCHAR(500) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_project_ai_configurations_id UNIQUE (project_ai_config_id),
    CONSTRAINT uk_project_ai_configurations_project UNIQUE (project_id),
    CONSTRAINT ck_project_ai_routing_mode CHECK (story_bible_routing_mode IN ('RETRIEVAL', 'LLM_SELECTOR', 'RETRIEVAL_THEN_LLM')),
    CONSTRAINT ck_project_ai_chunking CHECK (
        chunk_target_characters > 0
        AND chunk_overlap_characters >= 0
        AND chunk_overlap_characters < chunk_target_characters
        AND chunk_max_characters >= chunk_target_characters
    ),
    CONSTRAINT ck_project_ai_retrieval CHECK (
        retrieval_candidates >= retrieval_top_k
        AND retrieval_top_k > 0
        AND retrieval_max_per_source > 0
        AND hnsw_ef_search > 0
    )
);

CREATE INDEX idx_project_ai_embedding ON project_ai_configurations (embedding_model_config_id, project_id);
CREATE INDEX idx_project_ai_index_status ON project_ai_configurations (index_status, updated_at);

CREATE TABLE rag_embedding_spaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    embedding_space_id BIGINT NOT NULL,
    identity_hash CHAR(64) NOT NULL,
    provider_id BIGINT NOT NULL,
    protocol_code VARCHAR(64) NOT NULL,
    normalized_base_url VARCHAR(500) NOT NULL,
    model_name VARCHAR(120) NOT NULL,
    embedding_dimension INTEGER NOT NULL,
    distance_metric VARCHAR(24) NOT NULL,
    storage_type VARCHAR(16) NOT NULL,
    partition_name VARCHAR(63) NOT NULL,
    space_status VARCHAR(24) NOT NULL DEFAULT 'PROVISIONING',
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    activated_at TIMESTAMPTZ(3) NULL,
    cleanup_requested_at TIMESTAMPTZ(3) NULL,
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_rag_embedding_spaces_id UNIQUE (embedding_space_id),
    CONSTRAINT uk_rag_embedding_spaces_identity UNIQUE (identity_hash),
    CONSTRAINT uk_rag_embedding_spaces_partition UNIQUE (partition_name),
    CONSTRAINT ck_rag_embedding_dimension CHECK (embedding_dimension BETWEEN 1 AND 4000),
    CONSTRAINT ck_rag_embedding_metric CHECK (distance_metric IN ('COSINE', 'INNER_PRODUCT', 'L2')),
    CONSTRAINT ck_rag_embedding_storage CHECK (
        (storage_type = 'VECTOR' AND embedding_dimension <= 2000)
        OR (storage_type = 'HALFVEC' AND embedding_dimension BETWEEN 2001 AND 4000)
    )
);

CREATE INDEX idx_embedding_spaces_cleanup ON rag_embedding_spaces (space_status, cleanup_requested_at, deleted_at);

CREATE TABLE rag_index_builds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index_build_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    model_config_id BIGINT NOT NULL,
    embedding_space_id BIGINT NULL,
    build_status VARCHAR(32) NOT NULL DEFAULT 'QUEUED',
    source_count INTEGER NOT NULL DEFAULT 0,
    completed_source_count INTEGER NOT NULL DEFAULT 0,
    chunk_count INTEGER NOT NULL DEFAULT 0,
    embedded_chunk_count INTEGER NOT NULL DEFAULT 0,
    estimated_character_count BIGINT NOT NULL DEFAULT 0,
    last_error_code VARCHAR(96) NULL,
    last_error_message VARCHAR(500) NULL,
    started_at TIMESTAMPTZ(3) NULL,
    activated_at TIMESTAMPTZ(3) NULL,
    finished_at TIMESTAMPTZ(3) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_rag_index_builds_id UNIQUE (index_build_id)
);

CREATE INDEX idx_rag_build_project_status ON rag_index_builds (project_id, build_status, created_at);
CREATE INDEX idx_rag_build_space_status ON rag_index_builds (embedding_space_id, build_status);

CREATE TABLE rag_index_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_index_id BIGINT NOT NULL,
    index_build_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    source_id BIGINT NOT NULL,
    source_revision VARCHAR(128) NOT NULL,
    source_title VARCHAR(255) NOT NULL,
    source_status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    content_checksum CHAR(64) NULL,
    character_count BIGINT NOT NULL DEFAULT 0,
    chunk_count INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    activated_at TIMESTAMPTZ(3) NULL,
    superseded_at TIMESTAMPTZ(3) NULL,
    last_error_code VARCHAR(96) NULL,
    last_error_message VARCHAR(500) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_rag_index_sources_id UNIQUE (source_index_id),
    CONSTRAINT uk_rag_index_sources_revision UNIQUE (index_build_id, source_type, source_id, source_revision),
    CONSTRAINT ck_rag_index_source_type CHECK (source_type IN ('STORY_BIBLE_NODE', 'MANUSCRIPT_CHUNK', 'KNOWLEDGE_DOCUMENT'))
);

CREATE UNIQUE INDEX uk_rag_index_sources_active
    ON rag_index_sources (index_build_id, source_type, source_id)
    WHERE active = TRUE AND superseded_at IS NULL;
CREATE INDEX idx_rag_source_project_status ON rag_index_sources (project_id, source_status, updated_at);

CREATE TABLE rag_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chunk_id BIGINT NOT NULL,
    source_index_id BIGINT NOT NULL,
    index_build_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    embedding_space_id BIGINT NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    source_id BIGINT NOT NULL,
    chunk_no INTEGER NOT NULL,
    content_text TEXT NOT NULL,
    character_count INTEGER NOT NULL,
    token_count INTEGER NULL,
    content_hash CHAR(64) NOT NULL,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_rag_chunks_chunk_id UNIQUE (chunk_id),
    CONSTRAINT uk_rag_chunks_source_no UNIQUE (source_index_id, chunk_no)
);

CREATE INDEX idx_rag_chunks_build_source ON rag_chunks (index_build_id, source_index_id, chunk_no);
CREATE INDEX idx_rag_chunks_project_type ON rag_chunks (project_id, source_type, source_id);

-- Child partitions and metric-specific HNSW indexes are provisioned only by the
-- trusted pgvector infrastructure adapter after dimension detection.
CREATE TABLE rag_vectors_f32 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    embedding_space_id BIGINT NOT NULL,
    vector_id BIGINT NOT NULL,
    chunk_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    index_build_id BIGINT NOT NULL,
    embedding vector NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (embedding_space_id, id),
    CONSTRAINT uk_rag_vectors_f32_id UNIQUE (embedding_space_id, vector_id),
    CONSTRAINT uk_rag_vectors_f32_chunk UNIQUE (embedding_space_id, chunk_id)
) PARTITION BY LIST (embedding_space_id);

CREATE TABLE rag_vectors_f16 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    embedding_space_id BIGINT NOT NULL,
    vector_id BIGINT NOT NULL,
    chunk_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    index_build_id BIGINT NOT NULL,
    embedding halfvec NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (embedding_space_id, id),
    CONSTRAINT uk_rag_vectors_f16_id UNIQUE (embedding_space_id, vector_id),
    CONSTRAINT uk_rag_vectors_f16_chunk UNIQUE (embedding_space_id, chunk_id)
) PARTITION BY LIST (embedding_space_id);

CREATE TABLE rag_retrieval_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retrieval_log_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    run_id BIGINT NULL,
    index_build_id BIGINT NULL,
    query_text VARCHAR(1000) NULL,
    source_types_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    hit_count INTEGER NOT NULL DEFAULT 0,
    sources_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    latency_ms INTEGER NULL,
    adopted BOOLEAN NOT NULL DEFAULT FALSE,
    trace_id VARCHAR(64) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_rag_retrieval_logs_id UNIQUE (retrieval_log_id)
);

CREATE INDEX idx_rag_retrieval_project_created ON rag_retrieval_logs (project_id, created_at);
CREATE INDEX idx_rag_retrieval_run_created ON rag_retrieval_logs (run_id, created_at);
