-- PostgreSQL 18.4 baseline: V3__create_storage_and_rag.sql

-- Source: V3__init_storage_and_rag_minimal.sql
CREATE TABLE IF NOT EXISTS storage_objects (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_object_id BIGINT NOT NULL,
    object_key VARCHAR(500) NOT NULL,
    bucket VARCHAR(100) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    region VARCHAR(64) NULL,
    etag VARCHAR(128) NULL,
    size BIGINT NULL,
    storage_class VARCHAR(32) NULL,
    ref_type VARCHAR(50) NOT NULL,
    ref_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_storage_objects_storage_object_id UNIQUE (storage_object_id),
    CONSTRAINT uk_storage_object_key UNIQUE (object_key)
);

CREATE INDEX idx_storage_ref ON storage_objects (ref_type, ref_id);

CREATE TABLE IF NOT EXISTS rag_documents (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    doc_type VARCHAR(32) NOT NULL,
    title VARCHAR(200) NOT NULL,
    source_ref VARCHAR(500) NULL,
    origin_object_key VARCHAR(500) NOT NULL,
    origin_etag VARCHAR(128) NULL,
    mime_type VARCHAR(100) NULL,
    parse_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    index_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_rag_documents_document_id UNIQUE (document_id)
);

CREATE INDEX idx_rag_project_status ON rag_documents (project_id, parse_status, index_status, deleted_at);

CREATE TABLE IF NOT EXISTS rag_chunks (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chunk_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    chunk_no INTEGER NOT NULL,
    content_text TEXT NOT NULL,
    token_count INTEGER NOT NULL,
    vector_id VARCHAR(128) NOT NULL,
    vector_store VARCHAR(32) NOT NULL,
    embedding_provider VARCHAR(64) NOT NULL,
    embedding_model VARCHAR(64) NOT NULL,
    embedding_dim INTEGER NOT NULL,
    embedding_version VARCHAR(32) NOT NULL,
    metadata_json JSONB NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_rag_chunks_chunk_id UNIQUE (chunk_id),
    CONSTRAINT uk_chunks_vector UNIQUE (vector_id, vector_store)
);

CREATE INDEX idx_chunks_doc_no ON rag_chunks (document_id, chunk_no);
CREATE INDEX idx_chunks_project_doc ON rag_chunks (project_id, document_id);

CREATE TABLE IF NOT EXISTS rag_retrieval_logs (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retrieval_log_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    run_id BIGINT NULL,
    query_text VARCHAR(500) NULL,
    hit_count INTEGER NOT NULL DEFAULT 0,
    sources_json JSONB NULL,
    latency_ms INTEGER NULL,
    adopted BOOLEAN NOT NULL DEFAULT FALSE,
    trace_id VARCHAR(64) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_rag_retrieval_logs_retrieval_log_id UNIQUE (retrieval_log_id)
);

CREATE INDEX idx_rag_retrieval_project_created ON rag_retrieval_logs (project_id, created_at);
CREATE INDEX idx_rag_retrieval_run_created ON rag_retrieval_logs (run_id, created_at);
