-- PostgreSQL 18.4 baseline: V4__create_plugin_and_model.sql

CREATE TABLE IF NOT EXISTS model_providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(120) NOT NULL,
    base_url VARCHAR(255) NULL,
    auth_type VARCHAR(40) NOT NULL DEFAULT 'bearer',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_model_providers_provider_id UNIQUE (provider_id)
);

CREATE UNIQUE INDEX uk_model_providers_code ON model_providers (lower(code));

-- Source: V10__init_plugin_and_model_domains.sql
CREATE TABLE IF NOT EXISTS plugin_catalog (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plugin_id BIGINT NOT NULL,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(120) NOT NULL,
    category VARCHAR(60) NULL,
    provider VARCHAR(60) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    latest_version VARCHAR(40) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_plugin_catalog_plugin_id UNIQUE (plugin_id)
);

CREATE UNIQUE INDEX uk_plugin_code ON plugin_catalog (lower(code));

CREATE TABLE IF NOT EXISTS plugin_project_installs (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plugin_install_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    plugin_id BIGINT NOT NULL,
    version VARCHAR(40) NULL,
    config_json JSONB NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    installed_by BIGINT NOT NULL,
    installed_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_plugin_project_installs_install_id UNIQUE (plugin_install_id),
    CONSTRAINT uk_project_plugin UNIQUE (project_id, plugin_id)
);

CREATE INDEX idx_plugin_install_project ON plugin_project_installs (project_id);

CREATE TABLE IF NOT EXISTS plugin_call_logs (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plugin_call_log_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    run_id BIGINT NULL,
    plugin_code VARCHAR(100) NOT NULL,
    tool_name VARCHAR(100) NULL,
    request_json JSONB NULL,
    response_json JSONB NULL,
    latency_ms INTEGER NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'success',
    error_msg VARCHAR(255) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_plugin_call_logs_log_id UNIQUE (plugin_call_log_id)
);

CREATE INDEX idx_plugin_call_project_time ON plugin_call_logs (project_id, created_at);
CREATE INDEX idx_plugin_call_run ON plugin_call_logs (run_id, created_at);

CREATE TABLE IF NOT EXISTS model_user_api_keys (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_api_key_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    key_name VARCHAR(120) NOT NULL,
    encrypted_api_key TEXT NOT NULL,
    masked_api_key VARCHAR(40) NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    last_used_at TIMESTAMPTZ(3) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_model_user_api_keys_key_id UNIQUE (user_api_key_id)
);

CREATE INDEX idx_model_key_user_deleted ON model_user_api_keys (user_id, deleted_at);

CREATE TABLE IF NOT EXISTS model_official_api_keys (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    official_api_key_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    key_name VARCHAR(120) NOT NULL,
    encrypted_api_key TEXT NOT NULL,
    masked_api_key VARCHAR(40) NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    last_used_at TIMESTAMPTZ(3) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_model_official_api_keys_key_id UNIQUE (official_api_key_id)
);

CREATE INDEX idx_model_official_key_provider_deleted ON model_official_api_keys (provider_id, deleted_at);

CREATE TABLE IF NOT EXISTS model_user_configurations (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_config_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    model_name VARCHAR(120) NOT NULL,
    base_url VARCHAR(255) NULL,
    key_source_type VARCHAR(20) NOT NULL,
    user_key_id BIGINT NULL,
    official_key_id BIGINT NULL,
    context_window_turns INTEGER NOT NULL DEFAULT 6,
    max_context_tokens INTEGER NOT NULL DEFAULT 128000,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_model_user_configurations_model_config_id UNIQUE (model_config_id)
);

CREATE INDEX idx_model_user_config_user_deleted ON model_user_configurations (user_id, deleted_at);
CREATE INDEX idx_model_user_config_provider_deleted ON model_user_configurations (provider_id, deleted_at);
CREATE INDEX idx_model_user_config_user_key ON model_user_configurations (user_key_id);
CREATE INDEX idx_model_user_config_official_key ON model_user_configurations (official_key_id);
