-- PostgreSQL 18.4 baseline: plugin catalog and unified model configuration.
CREATE TABLE model_providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(120) NOT NULL,
    base_url VARCHAR(500) NULL,
    auth_type VARCHAR(40) NOT NULL DEFAULT 'BEARER',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_model_providers_provider_id UNIQUE (provider_id),
    CONSTRAINT ck_model_provider_auth_type CHECK (auth_type IN ('BEARER', 'NONE'))
);

CREATE UNIQUE INDEX uk_model_providers_code_active ON model_providers (lower(code)) WHERE deleted_at IS NULL;

CREATE TABLE model_provider_capabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_capability_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    capability_code VARCHAR(32) NOT NULL,
    protocol_code VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_model_provider_capabilities_id UNIQUE (provider_capability_id),
    CONSTRAINT ck_model_provider_capability CHECK (capability_code IN ('CHAT', 'EMBEDDING', 'RERANK', 'VISION', 'OCR', 'SPEECH'))
);

CREATE UNIQUE INDEX uk_model_provider_capability_active
    ON model_provider_capabilities (provider_id, capability_code)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_model_provider_capability_status ON model_provider_capabilities (capability_code, status, deleted_at);

CREATE TABLE model_configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_config_id BIGINT NOT NULL,
    scope_type VARCHAR(16) NOT NULL,
    owner_user_id BIGINT NULL,
    provider_id BIGINT NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    model_type VARCHAR(24) NOT NULL,
    model_name VARCHAR(120) NOT NULL,
    base_url VARCHAR(500) NULL,
    distance_metric VARCHAR(24) NULL,
    context_window_turns INTEGER NOT NULL DEFAULT 6,
    max_context_tokens INTEGER NOT NULL DEFAULT 128000,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_model_configurations_id UNIQUE (model_config_id),
    CONSTRAINT ck_model_configuration_scope CHECK (
        (scope_type = 'SYSTEM' AND owner_user_id IS NULL)
        OR (scope_type = 'USER' AND owner_user_id IS NOT NULL)
    ),
    CONSTRAINT ck_model_configuration_type CHECK (model_type IN ('CHAT', 'EMBEDDING')),
    CONSTRAINT ck_model_configuration_metric CHECK (
        (model_type = 'CHAT' AND distance_metric IS NULL)
        OR (model_type = 'EMBEDDING' AND distance_metric IN ('COSINE', 'INNER_PRODUCT', 'L2'))
    )
);

CREATE INDEX idx_model_config_scope_type ON model_configurations (scope_type, model_type, status, deleted_at);
CREATE INDEX idx_model_config_owner_type ON model_configurations (owner_user_id, model_type, status, deleted_at);
CREATE INDEX idx_model_config_provider ON model_configurations (provider_id, model_type, deleted_at);

CREATE TABLE model_user_api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_api_key_id BIGINT NOT NULL,
    model_config_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    encrypted_api_key TEXT NOT NULL,
    masked_api_key VARCHAR(40) NOT NULL,
    last_used_at TIMESTAMPTZ(3) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_model_user_api_keys_id UNIQUE (user_api_key_id)
);

CREATE UNIQUE INDEX uk_model_user_api_key_config_active
    ON model_user_api_keys (model_config_id)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_model_user_key_owner ON model_user_api_keys (user_id, status, deleted_at);

CREATE TABLE model_official_api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    official_api_key_id BIGINT NOT NULL,
    model_config_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    encrypted_api_key TEXT NOT NULL,
    masked_api_key VARCHAR(40) NOT NULL,
    last_used_at TIMESTAMPTZ(3) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_model_official_api_keys_id UNIQUE (official_api_key_id)
);

CREATE UNIQUE INDEX uk_model_official_api_key_config_active
    ON model_official_api_keys (model_config_id)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_model_official_key_provider ON model_official_api_keys (provider_id, status, deleted_at);

CREATE TABLE model_user_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    default_main_chat_model_config_id BIGINT NULL,
    default_worker_chat_model_config_id BIGINT NULL,
    default_embedding_model_config_id BIGINT NULL,
    default_router_model_config_id BIGINT NULL,
    default_story_bible_routing_mode VARCHAR(32) NOT NULL DEFAULT 'LLM_SELECTOR',
    default_chunk_target_characters INTEGER NOT NULL DEFAULT 800,
    default_chunk_overlap_characters INTEGER NOT NULL DEFAULT 120,
    default_chunk_max_characters INTEGER NOT NULL DEFAULT 1200,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_model_user_preferences_user UNIQUE (user_id),
    CONSTRAINT ck_model_user_preferences_routing CHECK (default_story_bible_routing_mode IN ('RETRIEVAL', 'LLM_SELECTOR', 'RETRIEVAL_THEN_LLM')),
    CONSTRAINT ck_model_user_preferences_chunking CHECK (
        default_chunk_target_characters > 0
        AND default_chunk_overlap_characters >= 0
        AND default_chunk_overlap_characters < default_chunk_target_characters
        AND default_chunk_max_characters >= default_chunk_target_characters
    )
);

CREATE INDEX idx_model_user_preferences_embedding ON model_user_preferences (default_embedding_model_config_id, user_id);

CREATE TABLE plugin_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plugin_id BIGINT NOT NULL,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(120) NOT NULL,
    category VARCHAR(60) NULL,
    provider VARCHAR(60) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    latest_version VARCHAR(40) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_plugin_catalog_plugin_id UNIQUE (plugin_id)
);

CREATE UNIQUE INDEX uk_plugin_code ON plugin_catalog (lower(code));

CREATE TABLE plugin_project_installs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plugin_install_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    plugin_id BIGINT NOT NULL,
    version VARCHAR(40) NULL,
    config_json JSONB NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    installed_by BIGINT NOT NULL,
    installed_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_plugin_project_installs_id UNIQUE (plugin_install_id),
    CONSTRAINT uk_project_plugin UNIQUE (project_id, plugin_id)
);

CREATE INDEX idx_plugin_install_project ON plugin_project_installs (project_id);

CREATE TABLE plugin_call_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plugin_call_log_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    run_id BIGINT NULL,
    plugin_code VARCHAR(100) NOT NULL,
    tool_name VARCHAR(100) NULL,
    request_json JSONB NULL,
    response_json JSONB NULL,
    latency_ms INTEGER NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
    error_msg VARCHAR(255) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_plugin_call_logs_id UNIQUE (plugin_call_log_id)
);

CREATE INDEX idx_plugin_call_project_time ON plugin_call_logs (project_id, created_at);
CREATE INDEX idx_plugin_call_run ON plugin_call_logs (run_id, created_at);
