-- PostgreSQL 18.4 baseline: V5__create_agent_domain.sql

-- Source: V11__init_agent_and_ops_domains.sql
CREATE TABLE IF NOT EXISTS agent_sessions (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    session_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    bound_style_id BIGINT NULL,
    story_bible_routing_mode VARCHAR(32) NULL,
    router_model_config_id BIGINT NULL,
    active_context_epoch_id BIGINT NULL,
    last_turn_id BIGINT NULL,
    last_run_id BIGINT NULL,
    last_message_at TIMESTAMPTZ(3) NULL,
    resumed_at TIMESTAMPTZ(3) NULL,
    total_prompt_tokens INTEGER NOT NULL DEFAULT 0,
    total_completion_tokens INTEGER NOT NULL DEFAULT 0,
    total_tokens INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_agent_sessions_session_id UNIQUE (session_id)
);

CREATE INDEX idx_agent_sessions_project_updated ON agent_sessions (project_id, updated_at);
CREATE INDEX idx_agent_sessions_project_status_deleted ON agent_sessions (project_id, session_status, deleted_at);

CREATE TABLE IF NOT EXISTS agent_user_preferences (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    story_bible_routing_mode VARCHAR(32) NOT NULL DEFAULT 'RETRIEVAL_THEN_LLM',
    router_model_config_id BIGINT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_user_preferences_user UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS agent_context_epochs (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epoch_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    epoch_no INTEGER NOT NULL,
    fingerprint CHAR(64) NOT NULL,
    story_bible_revision BIGINT NOT NULL,
    manuscript_revision BIGINT NOT NULL,
    active_chapter_id BIGINT NULL,
    style_binding_revision BIGINT NOT NULL DEFAULT 0,
    routing_mode VARCHAR(32) NOT NULL,
    router_model_config_id BIGINT NULL,
    router_model_config_revision BIGINT NOT NULL DEFAULT 0,
    prompt_bundle_hash CHAR(64) NOT NULL,
    skill_catalog_hash CHAR(64) NOT NULL,
    tool_catalog_hash CHAR(64) NOT NULL,
    snapshot_object_key VARCHAR(500) NOT NULL,
    snapshot_hash CHAR(64) NOT NULL,
    snapshot_size_bytes BIGINT NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    superseded_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_agent_context_epochs_epoch_id UNIQUE (epoch_id),
    CONSTRAINT uk_agent_context_epochs_session_no UNIQUE (session_id, epoch_no)
);

CREATE INDEX idx_agent_context_epochs_session_fingerprint ON agent_context_epochs (session_id, fingerprint, superseded_at);

CREATE TABLE IF NOT EXISTS agent_session_working_set (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    node_id BIGINT NOT NULL,
    activation_score NUMERIC(12,6) NOT NULL DEFAULT 0,
    last_used_turn_id BIGINT NULL,
    use_count INTEGER NOT NULL DEFAULT 0,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_session_working_set_node UNIQUE (session_id, node_id)
);

CREATE INDEX idx_agent_session_working_set_eviction ON agent_session_working_set (session_id, pinned, last_used_turn_id, activation_score);

CREATE TABLE IF NOT EXISTS agent_turns (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turn_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    turn_seq INTEGER NOT NULL,
    user_message_id BIGINT NULL,
    assistant_message_id BIGINT NULL,
    run_id BIGINT NULL,
    turn_status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    resume_token VARCHAR(128) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_turns_turn_id UNIQUE (turn_id),
    CONSTRAINT uk_agent_turns_session_seq UNIQUE (session_id, turn_seq)
);

CREATE INDEX idx_agent_turns_session_status ON agent_turns (session_id, turn_status);
CREATE INDEX idx_agent_turns_run ON agent_turns (run_id);

CREATE TABLE IF NOT EXISTS agent_messages (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    turn_id BIGINT NULL,
    role VARCHAR(20) NOT NULL,
    message_kind VARCHAR(30) NOT NULL DEFAULT 'CHAT',
    content_markdown TEXT NOT NULL,
    render_blocks_json JSONB NULL,
    tool_call_id VARCHAR(128) NULL,
    approval_id BIGINT NULL,
    delivery_status VARCHAR(20) NOT NULL DEFAULT 'FINAL',
    seq_no INTEGER NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_messages_message_id UNIQUE (message_id),
    CONSTRAINT uk_agent_messages_session_seq UNIQUE (session_id, seq_no)
);

CREATE INDEX idx_agent_messages_turn ON agent_messages (turn_id);
CREATE INDEX idx_agent_messages_session_created ON agent_messages (session_id, created_at);

CREATE TABLE IF NOT EXISTS agent_runs (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    turn_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    run_status VARCHAR(32) NOT NULL,
    run_phase VARCHAR(64) NOT NULL,
    context_epoch_id BIGINT NULL,
    active_approval_id BIGINT NULL,
    latest_event_seq BIGINT NOT NULL DEFAULT 0,
    latest_checkpoint_id BIGINT NULL,
    trace_id VARCHAR(64) NULL,
    started_at TIMESTAMPTZ(3) NULL,
    finished_at TIMESTAMPTZ(3) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_runs_run_id UNIQUE (run_id),
    CONSTRAINT uk_agent_runs_turn_id UNIQUE (turn_id)
);

CREATE INDEX idx_agent_runs_session_updated ON agent_runs (session_id, updated_at);
CREATE INDEX idx_agent_runs_project_status ON agent_runs (project_id, run_status);
CREATE INDEX idx_agent_runs_context_epoch ON agent_runs (context_epoch_id);

CREATE TABLE IF NOT EXISTS agent_run_inputs (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    prompt_snapshot TEXT NOT NULL,
    task_type VARCHAR(32) NOT NULL,
    chapter_id BIGINT NULL,
    selected_text TEXT NULL,
    style_snapshot_json JSONB NULL,
    model_snapshot_json JSONB NULL,
    plugin_bindings_json JSONB NULL,
    input_hash VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_run_inputs_run_id UNIQUE (run_id)
);

CREATE TABLE IF NOT EXISTS agent_events (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    turn_id BIGINT NOT NULL,
    sequence BIGINT NOT NULL,
    schema_version INTEGER NOT NULL DEFAULT 1,
    event_type VARCHAR(96) NOT NULL,
    payload_json JSONB NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_events_event_id UNIQUE (event_id),
    CONSTRAINT uk_agent_events_run_seq UNIQUE (run_id, sequence)
);

CREATE INDEX idx_agent_events_run_type ON agent_events (run_id, event_type);
CREATE INDEX idx_agent_events_session_created ON agent_events (session_id, created_at);

CREATE TABLE IF NOT EXISTS agent_checkpoints (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkpoint_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    checkpoint_no BIGINT NOT NULL,
    last_event_seq BIGINT NOT NULL,
    state_json JSONB NOT NULL,
    state_size_bytes INTEGER NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_checkpoints_checkpoint_id UNIQUE (checkpoint_id),
    CONSTRAINT uk_agent_checkpoints_run_no UNIQUE (run_id, checkpoint_no)
);

CREATE INDEX idx_agent_checkpoints_run_latest ON agent_checkpoints (run_id, checkpoint_no);

CREATE TABLE IF NOT EXISTS agent_run_projections (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    turn_id BIGINT NOT NULL,
    run_status VARCHAR(32) NOT NULL,
    run_phase VARCHAR(64) NOT NULL,
    status_message VARCHAR(500) NULL,
    active_approval_id BIGINT NULL,
    latest_sequence BIGINT NOT NULL DEFAULT 0,
    last_error_code VARCHAR(96) NULL,
    last_error_message VARCHAR(500) NULL,
    current_assistant_message_id BIGINT NULL,
    result_artifact_id BIGINT NULL,
    token_usage_json JSONB NULL,
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_run_projections_run_id UNIQUE (run_id)
);

CREATE INDEX idx_agent_run_projections_session ON agent_run_projections (session_id, updated_at);

CREATE TABLE IF NOT EXISTS agent_tool_call_projections (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    tool_call_id VARCHAR(128) NOT NULL,
    tool_code VARCHAR(100) NOT NULL,
    tool_name VARCHAR(200) NULL,
    status VARCHAR(32) NOT NULL,
    iteration INTEGER NULL,
    arguments_preview_json JSONB NULL,
    output_preview TEXT NULL,
    output_artifact_id BIGINT NULL,
    approval_id BIGINT NULL,
    error_code VARCHAR(96) NULL,
    error_message VARCHAR(500) NULL,
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_tool_call_projection UNIQUE (run_id, tool_call_id)
);

CREATE INDEX idx_agent_tool_call_run_status ON agent_tool_call_projections (run_id, status);

CREATE TABLE IF NOT EXISTS agent_todo_projections (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    todo_id VARCHAR(128) NOT NULL,
    title VARCHAR(500) NOT NULL,
    status VARCHAR(32) NOT NULL,
    sort_order INTEGER NOT NULL,
    blocked_reason VARCHAR(500) NULL,
    error_summary VARCHAR(500) NULL,
    completed_summary VARCHAR(500) NULL,
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_todo_projection UNIQUE (run_id, todo_id)
);

CREATE INDEX idx_agent_todo_run_status ON agent_todo_projections (run_id, status);

CREATE TABLE IF NOT EXISTS agent_artifacts (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    event_id BIGINT NULL,
    artifact_type VARCHAR(64) NOT NULL,
    payload_json JSONB NOT NULL,
    content_type VARCHAR(100) NOT NULL DEFAULT 'application/json',
    size_bytes INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_artifacts_artifact_id UNIQUE (artifact_id)
);

CREATE INDEX idx_agent_artifacts_run_type ON agent_artifacts (run_id, artifact_type);

CREATE TABLE IF NOT EXISTS agent_session_style_bindings (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    binding_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    style_id BIGINT NOT NULL,
    source VARCHAR(24) NOT NULL,
    activated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deactivated_at TIMESTAMPTZ(3) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_session_style_bindings_binding_id UNIQUE (binding_id)
);

CREATE INDEX idx_agent_session_style_bindings_session_active ON agent_session_style_bindings (session_id, deactivated_at);
CREATE INDEX idx_agent_session_style_bindings_style ON agent_session_style_bindings (style_id);

CREATE TABLE IF NOT EXISTS ops_async_jobs (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    job_type VARCHAR(60) NOT NULL,
    biz_key VARCHAR(120) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    error_msg VARCHAR(500) NULL,
    started_at TIMESTAMPTZ(3) NULL,
    finished_at TIMESTAMPTZ(3) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_ops_async_jobs_job_id UNIQUE (job_id)
);

CREATE INDEX idx_ops_job_type_status ON ops_async_jobs (job_type, status);
CREATE INDEX idx_ops_job_biz_key ON ops_async_jobs (biz_key);

CREATE TABLE IF NOT EXISTS ops_migrations (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migration_id BIGINT NOT NULL,
    migration_type VARCHAR(80) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'running',
    progress_pct INTEGER NOT NULL DEFAULT 0,
    summary_json JSONB NULL,
    error_msg VARCHAR(500) NULL,
    started_at TIMESTAMPTZ(3) NULL,
    finished_at TIMESTAMPTZ(3) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_ops_migrations_migration_id UNIQUE (migration_id)
);


-- Source: V12__init_pending_tool_invocations.sql
CREATE TABLE IF NOT EXISTS agent_run_pending_approvals (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pending_approval_id BIGINT NOT NULL,
    approval_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    turn_id BIGINT NOT NULL,
    tool_call_id VARCHAR(128) NOT NULL,
    tool_code VARCHAR(100) NOT NULL,
    tool_args_json JSONB NULL,
    tool_context_json JSONB NULL,
    resume_payload_json JSONB NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    pending_status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    operator_id BIGINT NULL,
    trace_id VARCHAR(64) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_run_pending_approvals_pending_id UNIQUE (pending_approval_id),
    CONSTRAINT uk_agent_run_pending_approvals_approval_id UNIQUE (approval_id),
    CONSTRAINT uk_agent_run_pending_approvals_idempotency UNIQUE (idempotency_key)
);

CREATE INDEX idx_agent_run_pending_approvals_run_status ON agent_run_pending_approvals (run_id, pending_status);
CREATE INDEX idx_agent_run_pending_approvals_session_status ON agent_run_pending_approvals (session_id, pending_status);


-- Source: V13__init_agent_session_todos.sql
CREATE TABLE IF NOT EXISTS agent_session_todos (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    source_run_id BIGINT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    source_type VARCHAR(32) NOT NULL,
    todo_status VARCHAR(32) NOT NULL,
    completed_at TIMESTAMPTZ(3) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMPTZ(3) NULL,
    CONSTRAINT uk_agent_session_todos_todo_id UNIQUE (todo_id)
);

CREATE INDEX idx_agent_session_todos_session_status_deleted ON agent_session_todos (session_id, todo_status, deleted_at);
CREATE INDEX idx_agent_session_todos_session_created ON agent_session_todos (session_id, created_at);
CREATE INDEX idx_agent_session_todos_source_run ON agent_session_todos (source_run_id);
