-- PostgreSQL 18.4 baseline: V6__create_agent_execution_extensions.sql

-- Source: V17__add_agent_run_leases.sql
ALTER TABLE agent_runs ADD COLUMN lease_owner VARCHAR(128) NULL;
ALTER TABLE agent_runs ADD COLUMN lease_until TIMESTAMPTZ(3) NULL;
ALTER TABLE agent_runs ADD COLUMN execution_token BIGINT NOT NULL DEFAULT 0;
ALTER TABLE agent_runs ADD COLUMN attempt_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE agent_runs ADD COLUMN next_retry_at TIMESTAMPTZ(3) NULL;
ALTER TABLE agent_runs ADD COLUMN last_error_code VARCHAR(96) NULL;
ALTER TABLE agent_runs ADD COLUMN last_error_message VARCHAR(500) NULL;
CREATE INDEX idx_agent_runs_recovery ON agent_runs(run_status, next_retry_at, lease_until);


-- Source: V18__add_agent_run_dependency_revisions.sql
ALTER TABLE novel_chapters ADD COLUMN content_revision BIGINT NOT NULL DEFAULT 1;
ALTER TABLE agent_context_epochs ADD COLUMN active_chapter_content_revision BIGINT NOT NULL DEFAULT 0;
ALTER TABLE agent_runs ADD COLUMN predecessor_run_id BIGINT NULL;
ALTER TABLE agent_runs DROP CONSTRAINT uk_agent_runs_turn_id;
CREATE INDEX idx_agent_runs_turn_id ON agent_runs(turn_id);
CREATE INDEX idx_agent_runs_predecessor ON agent_runs(predecessor_run_id);


-- Source: V19__harden_agent_checkpoints.sql
ALTER TABLE agent_checkpoints ADD COLUMN state_schema_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE agent_checkpoints ADD COLUMN state_sha256 CHAR(64) NULL;
ALTER TABLE agent_checkpoints ADD COLUMN state_object_key VARCHAR(500) NULL;


-- Source: V20__add_agent_event_archives.sql
CREATE TABLE IF NOT EXISTS agent_event_archives (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    first_sequence BIGINT NOT NULL,
    last_sequence BIGINT NOT NULL,
    event_count INTEGER NOT NULL,
    object_key VARCHAR(500) NOT NULL,
    size_bytes BIGINT NOT NULL,
    sha256 CHAR(64) NOT NULL,
    archive_status VARCHAR(24) NOT NULL,
    verified_at TIMESTAMPTZ(3) NULL,
    expires_at TIMESTAMPTZ(3) NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_event_archives_id UNIQUE (archive_id),
    CONSTRAINT uk_agent_event_archives_run UNIQUE (run_id)
);

CREATE INDEX idx_agent_event_archives_expiry ON agent_event_archives (archive_status, expires_at);


-- Source: V21__add_checkpoint_cold_storage.sql
ALTER TABLE agent_checkpoints ADD COLUMN storage_tier VARCHAR(16) NOT NULL DEFAULT 'HOT';
ALTER TABLE agent_checkpoints ADD COLUMN cold_archived_at TIMESTAMPTZ(3) NULL;
ALTER TABLE agent_checkpoints ADD COLUMN expires_at TIMESTAMPTZ(3) NULL;
CREATE INDEX idx_agent_checkpoints_storage_expiry ON agent_checkpoints (storage_tier, expires_at);


-- Source: V22__add_agent_tool_call_executions.sql
CREATE TABLE IF NOT EXISTS agent_tool_call_executions (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    tool_call_id VARCHAR(128) NOT NULL,
    tool_code VARCHAR(100) NOT NULL,
    request_sha256 CHAR(64) NOT NULL,
    execution_token BIGINT NOT NULL,
    execution_status VARCHAR(24) NOT NULL,
    result_json JSONB NULL,
    error_code VARCHAR(96) NULL,
    error_message VARCHAR(500) NULL,
    started_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    finished_at TIMESTAMPTZ(3) NULL,
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_tool_call_executions_id UNIQUE (execution_id),
    CONSTRAINT uk_agent_tool_call_executions_call UNIQUE (run_id, tool_call_id)
);

CREATE INDEX idx_agent_tool_call_executions_status ON agent_tool_call_executions (execution_status, updated_at);


-- Source: V23__enforce_single_agent_run_successor.sql
ALTER TABLE agent_runs ADD CONSTRAINT uk_agent_runs_predecessor UNIQUE (predecessor_run_id);
