-- PostgreSQL 18.4 baseline: durable Agent execution extensions and async queue.
CREATE TABLE agent_event_archives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    first_sequence BIGINT NOT NULL,
    last_sequence BIGINT NOT NULL,
    event_count INTEGER NOT NULL,
    object_key VARCHAR(500) NOT NULL,
    size_bytes BIGINT NOT NULL,
    sha256 CHAR(64) NOT NULL,
    archive_status VARCHAR(24) NOT NULL,
    verified_at TIMESTAMPTZ(3) NULL,
    expires_at TIMESTAMPTZ(3) NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_event_archives_id UNIQUE (archive_id),
    CONSTRAINT uk_agent_event_archives_run UNIQUE (run_id)
);

CREATE INDEX idx_agent_event_archives_expiry ON agent_event_archives (archive_status, expires_at);

CREATE TABLE agent_tool_call_executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    tool_call_id VARCHAR(128) NOT NULL,
    tool_code VARCHAR(100) NOT NULL,
    request_sha256 CHAR(64) NOT NULL,
    execution_token BIGINT NOT NULL,
    execution_status VARCHAR(24) NOT NULL,
    result_json JSONB NULL,
    error_code VARCHAR(96) NULL,
    error_message VARCHAR(500) NULL,
    started_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    finished_at TIMESTAMPTZ(3) NULL,
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_agent_tool_call_executions_id UNIQUE (execution_id),
    CONSTRAINT uk_agent_tool_call_executions_call UNIQUE (run_id, tool_call_id)
);

CREATE INDEX idx_agent_tool_call_executions_status ON agent_tool_call_executions (execution_status, updated_at);

CREATE TABLE ops_async_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    job_type VARCHAR(60) NOT NULL,
    biz_key VARCHAR(200) NOT NULL,
    owner_user_id BIGINT NULL,
    project_id BIGINT NULL,
    payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    result_json JSONB NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'QUEUED',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 5,
    scheduled_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    lease_owner VARCHAR(128) NULL,
    lease_until TIMESTAMPTZ(3) NULL,
    heartbeat_at TIMESTAMPTZ(3) NULL,
    cancel_requested_at TIMESTAMPTZ(3) NULL,
    progress_current BIGINT NOT NULL DEFAULT 0,
    progress_total BIGINT NOT NULL DEFAULT 0,
    progress_message VARCHAR(500) NULL,
    last_error_code VARCHAR(96) NULL,
    last_error_message VARCHAR(1000) NULL,
    started_at TIMESTAMPTZ(3) NULL,
    finished_at TIMESTAMPTZ(3) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_ops_async_jobs_id UNIQUE (job_id),
    CONSTRAINT uk_ops_async_jobs_biz_key UNIQUE (biz_key),
    CONSTRAINT ck_ops_async_jobs_attempts CHECK (attempt_count >= 0 AND max_attempts BETWEEN 1 AND 20),
    CONSTRAINT ck_ops_async_jobs_progress CHECK (progress_current >= 0 AND progress_total >= 0)
);

CREATE INDEX idx_ops_jobs_claim
    ON ops_async_jobs (status, scheduled_at, lease_until, created_at)
    WHERE status IN ('QUEUED', 'RETRY_WAIT', 'RUNNING');
CREATE INDEX idx_ops_jobs_project_created ON ops_async_jobs (project_id, created_at DESC);
CREATE INDEX idx_ops_jobs_owner_created ON ops_async_jobs (owner_user_id, created_at DESC);
CREATE INDEX idx_ops_jobs_lease ON ops_async_jobs (lease_until) WHERE status = 'RUNNING';

CREATE TABLE ops_async_job_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_attempt_id BIGINT NOT NULL,
    job_id BIGINT NOT NULL,
    attempt_no INTEGER NOT NULL,
    worker_id VARCHAR(128) NOT NULL,
    status VARCHAR(24) NOT NULL,
    started_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    finished_at TIMESTAMPTZ(3) NULL,
    error_code VARCHAR(96) NULL,
    error_message VARCHAR(1000) NULL,
    CONSTRAINT uk_ops_async_job_attempts_id UNIQUE (job_attempt_id),
    CONSTRAINT uk_ops_async_job_attempt UNIQUE (job_id, attempt_no)
);

CREATE INDEX idx_ops_async_job_attempts_job ON ops_async_job_attempts (job_id, attempt_no DESC);

CREATE TABLE ops_migrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migration_id BIGINT NOT NULL,
    migration_type VARCHAR(80) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'RUNNING',
    progress_pct INTEGER NOT NULL DEFAULT 0,
    summary_json JSONB NULL,
    error_msg VARCHAR(500) NULL,
    started_at TIMESTAMPTZ(3) NULL,
    finished_at TIMESTAMPTZ(3) NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_ops_migrations_id UNIQUE (migration_id),
    CONSTRAINT ck_ops_migrations_progress CHECK (progress_pct BETWEEN 0 AND 100)
);
