CREATE TABLE IF NOT EXISTS author_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    default_language VARCHAR(32) NOT NULL DEFAULT 'zh-CN',
    collaboration_mode VARCHAR(32) NOT NULL DEFAULT 'COLLABORATIVE',
    default_pov VARCHAR(32) NOT NULL DEFAULT 'PROJECT_DEFAULT',
    default_tense VARCHAR(32) NOT NULL DEFAULT 'PROJECT_DEFAULT',
    description_density VARCHAR(16) NOT NULL DEFAULT 'MEDIUM',
    dialogue_preference VARCHAR(1000) NOT NULL DEFAULT '',
    banned_expressions VARCHAR(2000) NOT NULL DEFAULT '',
    long_term_memory VARCHAR(5000) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_author_profiles_user UNIQUE (user_id),
    CONSTRAINT ck_author_profiles_collaboration CHECK (
        collaboration_mode IN ('DIRECT', 'COLLABORATIVE', 'EXPLORATORY')
    ),
    CONSTRAINT ck_author_profiles_pov CHECK (
        default_pov IN ('PROJECT_DEFAULT', 'FIRST_PERSON', 'THIRD_LIMITED', 'THIRD_OMNISCIENT')
    ),
    CONSTRAINT ck_author_profiles_tense CHECK (
        default_tense IN ('PROJECT_DEFAULT', 'PAST', 'PRESENT')
    ),
    CONSTRAINT ck_author_profiles_density CHECK (
        description_density IN ('LIGHT', 'MEDIUM', 'RICH')
    )
);
